version: '3.8'
services:
  db:
   image: mysql
   environment:
     - MYSQL_ROOT_PASSWORD=@123
     - MYSQL_DATABASE=wordpress
     - MYSQL_USER=wordpress
     - MYSQL_PASSWORD=wordpress
   ports: 
     - "3306:3306"
   volumes:
     - db_data:/var/lib/mysql
  wordpress:
   image: wordpress
   ports:
     - "4000:80"
   restart: always
   environment:
     - WORDPRESS_DB_HOST=db
     - WORDPRESS_DB_USER=wordpress
     - WORDPRESS_DB_PASSWORD=wordpress
     - WORDPRESS_DB_NAME=wordpress
   volumes:
     - wordpress:/var/www/html
volumes:
   db_data:
   wordpress:

